CREATE TABLE escolas (
    id SERIAL PRIMARY KEY,
    dre TEXT,
    codesc NUMERIC,
    tipoesc TEXT,
    nomes TEXT,
    nomescofi TEXT,
    ceu TEXT,
    diretoria TEXT,
    subpref TEXT,
    endereco TEXT,
    numero TEXT,
    bairro TEXT,
    cep NUMERIC,
    tel1 TEXT,
    tel2 TEXT,
    fax NUMERIC,
    situacao TEXT,
    coddist NUMERIC,
    distrito TEXT,
    setor NUMERIC,
    codinep NUMERIC,
    cd_cie NUMERIC,
    eh NUMERIC,
    fx_etaria TEXT,
    dt_criacao TIMESTAMP,
    ato_criacao TEXT,
    dom_criacao TIMESTAMP,
    dt_ini_conv TEXT,
    dt_autoriza TEXT,
    dt_extincao NUMERIC,
    nome_ant TEXT,
    rede TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    "database" TIMESTAMP
);
